spring.application.name=ecommerce

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection String with PostgreSQL Mode
# 'testdb' is the name of your local database
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate settings for development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#JWT Secret
jwt.secret = your-256-bit-secret-key-here-make-it-at-least-32-bytes-long